src/api/urls.py
from django.urls import path, re_path


from .views import PostgrestTest

app_name = 'api'
urlpatterns = [
    # path("", InboxView.as_view()),
    # re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
    re_path(r"^postgrest/$",PostgrestTest)
]

src/cfehome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('messages/', include('chat.urls')),
    path('api/',include('api.urls'))
]

src/chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
    # re_path(r"^/postgrest/$",PostgrestTest)
]

src/api/models.py
from django.db import models

# Create your models here.

src/chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

src/chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

src/api/views.py
from django.shortcuts import render
from django.http import JsonResponse,HttpResponse
import requests
import json
# Create your views here.
def PostgrestTest(request):
    response = requests.get('http://45.82.136.21:3000/todos')
    print(response.text)
    loaded_dict_data = json.loads(response.text)
    return JsonResponse(loaded_dict_data,safe=False)
    # return JsonResponse(json.dumps(response))
    #return HttpResponse('hello fucker')

src/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage



class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

src/chat/templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

src/chat/templates/chat/thread.html
{% extends "base.html" %}

{% block content %}
<p id='api'></p>
<p id='api2'></p>
{% comment %} <h3>Thread for {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3> {% endcomment %}
{% comment %} <ul id='chat-items'> {% endcomment %}
{% comment %} {% for chat in object.chatmessage_set.all %} {% endcomment %}

{% comment %} <li>{{ chat.message }} via {{ chat.user }}</li> {% endcomment %}

{% comment %} {% endfor %} {% endcomment %}
{% comment %} </ul> {% endcomment %}

<form id='form' method='POST'> {% csrf_token %}
{{form.as_p }}
<input type='submit' class='btn btn-primary'/>
</form>

{% endblock %}

{% block script %}

<script>
// websocket scripts
console.log(window.location)
var loc = window.location
var formData = $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")
var api = $("#api")
var api2 = $("#api2")

var wsStart = 'ws://'
if(loc.protocol == 'https:'){
    wsStart = 'wss://'
}
var endpoint = wsStart + loc.host + loc.pathname
var endpoint2 = wsStart + loc.host + '/user2/'
var endpoint3 = wsStart + loc.host + '/user3/'
console.log(endpoint + ' endpoint')
console.log(endpoint2+'endpoint2')
var socket = new WebSocket(endpoint)
 ///////////////////////////////
var socket2 = new WebSocket(endpoint2)
///////////////////////////////
var socket3 = new WebSocket(endpoint3)

socket2.onopen = function(e){
    console.log('message2',e)
    console.log('socket 2 is connected bitch!')
}
socket2.onmessage = function(e){
console.log("message2", e)
chatHolder.append("<li>" + e.data + "</li>")
api2.append(e.data)
}

socket3.onopen = function(e){
    console.log("socket3 is connected!")
}

socket3.onmessage = function (e) {
    console.log('message3',e)
    console.log('type',e.type)
}

socket.onmessage = function(e){
    console.log("message", e)
    chatHolder.append("<li>" + e.data + "</li>")
    api.append(e.data)
}
socket.onopen = function(e){
    console.log("open" , e)
    formData.submit(function(event){
        event.preventDefault()
        var msgText = msgInput.val()

        var finalData = {
            'message': msgText
        }

        socket.send(JSON.stringify(finalData))
        
        formData[0].reset()
    })
}
socket.onerror = function(e){
    console.log("error" , e)
}
socket.onclose = function(e){
    console.log("close",e)
}

</script>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>WEBSOCKET TEST</title>
    {% include 'css.html' %}
</head>
<body>

<div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col'>
            <h1 class='p-0 m-0'>WS</h1>
        </div>
    </div>
{% block content %}
{% endblock %}
</div>


{% include 'js.html' %}
{% block script %}
{% endblock %}

</body>
</html>

src/templates/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

src/templates/home.html
{% extends "base.html" %}

{% block content %}

<p class='lead'>Welcome Home</p>
{% endblock %}

src/templates/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>